name: 'co2_emission'
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.9
    - scikit-learn
    - ipykernel
    - altair-all
    - pandas
    - matplotlib
    - numpy
    - dash
    - dash-bootstrap-components
    - plotly
    - pip
pip:
    - dash-vega-components
